project:
  type: website

website:
  title: "BERTopic Tutorial"
  navbar:
    left:
      - href: tutorial.qmd
        text: Home
      - techy-notes.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
